name: 'test upload results to github pages'

on:
  workflow_dispatch:

env:
  DOTNET_VERSION: '8.0.x'

jobs:
   automation-tests:
     name: test upload results to github pages
     runs-on: ubuntu-latest

     steps:
     - uses: actions/checkout@v4
     - name: Set up .NET SDK
       uses: actions/setup-dotnet@v3
       with:
         dotnet-version: '8.0.x'

     - name: Navigate to src directory
       run: cd src

     - name: List directory contents
       run: ls -al # Lists all files and directories in the current directory

     - name: Restore dependenciess
       working-directory: src
       run: dotnet restore

     - name: Build
       if: success() || failure()
       working-directory: src
       run: dotnet build --configuration Release
